SKILL_CATALOG = [
    "React",
    "Node.js",
    "Express.js",
    "JavaScript",
    "TypeScript",
    "HTML",
    "CSS",
    "Tailwind CSS",
    "MongoDB",
    "SQL",
    "Python",
    "Java",
    "Django",
    "Flask",
    "FastAPI",
    "Git",
    "REST API",
    "GraphQL",
    "Docker",
    "Kubernetes",
    "AWS",
    "CI/CD",
    "Machine Learning",
    "TensorFlow",
    "PyTorch",
]
